### ISSUE TITLE
vaste line height aan alle tekst 

### ISSUE THREAD

**Issue by J3SS3HVA** [lisagjh/touchtribe-proof-of-concept#18]
Standaard is de line height die je aan tekst moet geven anderhalf keer groter dan zijn font size.

Hier kan je `line-height: 1.5;` toepassen. 

```css
* {
    font-family: var(--inter);
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}
```

buiten dat zie je css er goed een overzichtelijk uit.
